#' Dye bias correction
#'
#' Adjusts dye bias by scaling each color channel to have the same mean intensity.
#'
#' Infinium HumanMethylation450 BeadChip
#' @param rg Cy5/Cy3 signal generated by \code{\link{meffil.read.rg}()}.
#' @param intensity Intensity of both color channels after correct (Default: 5000).
#' @param probes Probe annotation used to construct the control matrix
#' (Default: \code{\link{meffil.probe.info}()}).
#' @return Cy5/Cy3 signals with average intensity equal to \code{intensity}.
#'
#' @export
meffil.dye.bias.correct <- function(rg, intensity=5000, probes=meffil.probe.info()) {
    msg()
    stopifnot(is.rg(rg))
    stopifnot(intensity >= 100)

    rg$R <- rg$R * intensity/calculate.intensity.R(rg, probes)
    rg$G <- rg$G * intensity/calculate.intensity.G(rg, probes)
    rg
}

calculate.intensity.R <- function(rg, probes=meffil.probe.info()) {
    addresses <- probes$address[which(probes$target %in% c("NORM_A", "NORM_T")
                                      & probes$dye == "R")]
    idx <- match(addresses, names(rg$R))
    stopifnot(length(idx) >= 10) ## there are 93 in total
    mean(rg$R[idx], na.rm=T)
}

calculate.intensity.G <- function(rg, probes=meffil.probe.info()) {
    addresses <- probes$address[which(probes$target %in% c("NORM_G", "NORM_C")
                                      & probes$dye == "G")]
    idx <- match(addresses, names(rg$G))
    stopifnot(length(idx) >= 10) ## there are 93 in total
    mean(rg$G[idx], na.rm=T)
}

