

#' Convert to methylated/unmethylated signal
#'
#' Converts Cy5/Cy3 signals to methylated/unmethylated signals from a
#' Infinium HumanMethylation450 BeadChip.
#'
#' @param rg Cy5/Cy3 signal generated by \code{\link{meffil.read.rg}()}.
#' @param probes Probe annotation used to construct the control matrix
#' (Default: \code{\link{meffil.probe.info}()}).
#' @param verbose If \code{TRUE}, then print time function started (Default: \code{FALSE}).
#' @return List containing methylated and unmethylated signals.
#'
#' @export
meffil.rg.to.mu <- function(rg, probes=meffil.probe.info(), verbose=F) {
    stopifnot(is.rg(rg))

    msg("converting red/green to methylated/unmethylated signal", verbose=verbose)
    probes.M.R <- probes[which(probes$target == "M" & probes$dye == "R"),]
    probes.M.G <- probes[which(probes$target == "M" & probes$dye == "G"),]
    probes.U.R <- probes[which(probes$target == "U" & probes$dye == "R"),]
    probes.U.G <- probes[which(probes$target == "U" & probes$dye == "G"),]

    M <- c(rg$R[probes.M.R$address], rg$G[probes.M.G$address])
    U <- c(rg$R[probes.U.R$address], rg$G[probes.U.G$address])

    names(M) <- c(probes.M.R$name, probes.M.G$name)
    names(U) <- c(probes.U.R$name, probes.U.G$name)

    U <- U[names(M)]

    stopifnot(length(U) > 100000)
    stopifnot(length(M) > 100000)

    list(M=M,U=U)
}
